[[AxisAlgorithms]]
deps = ["WoodburyMatrices"]
git-tree-sha1 = "5d7f12d7f1a53ee5fd31d5b05b7f09033703fba8"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Compat", "SHA"]
git-tree-sha1 = "88f5e40c04b5aac568656d6464576974eb9afce4"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.2"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "2573aaad07cbbe21526e055bea3e995abc9e7c99"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.0"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "6a78981b00a954d850d923cae8500801647d843e"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.10"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Test"]
git-tree-sha1 = "eb9923f30264ee2c78d8c20c59797583cffdf105"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.0"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "cec56a50029f40f4c13e4f25bf84964fde31905a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "f3e87ca1e2df8e1e4f82ea504fddf0b9b0894f61"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.69.0"

[[Contour]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "7362b76e9939964a94fd39430bc901092c371d21"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.4.0"

[[CustomUnitRanges]]
git-tree-sha1 = "745a202720c1e848936c7808177841c36446948c"
uuid = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
version = "0.1.0"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Missings", "Reexport", "SortingAlgorithms", "StatsBase", "TranscodingStreams", "WeakRefStrings"]
git-tree-sha1 = "be4d979564837fbb6be9eb4872ab7352bbc32e71"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.11.6"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["Compat", "REPL"]
git-tree-sha1 = "abc05631fbe6e6a62c60f37bf644df87d5470fe4"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.8.3"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["Compat"]
git-tree-sha1 = "0e9a957a5c1cc5d06e54aab3b8b9c4c495253269"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.4.4"

[[Documenter]]
deps = ["Compat", "DocStringExtensions", "Logging", "REPL"]
git-tree-sha1 = "4fc4abdb5ac20ece943ff6e0a7e2a254d148f434"
uuid = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
version = "0.18.0"

[[DualNumbers]]
deps = ["Calculus", "Compat", "NaNMath"]
git-tree-sha1 = "fc9c09319884bdc80f66993197dfc300051781b9"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.4.0"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "53fae3f45b6782dad91e932d941b0bf862110641"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.1"

[[Future]]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[GR]]
deps = ["DelimitedFiles", "Random", "Serialization", "Sockets", "Test"]
git-tree-sha1 = "b0a1d37d216fe143020b5d7d49c4fdc18642f150"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.31.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "Compat", "DualNumbers", "Ratios", "ShowItLikeYouBuildIt", "WoodburyMatrices"]
git-tree-sha1 = "430c639cdd802f625904023880ea4b2760df9e10"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.7.3"

[[JSON]]
deps = ["Compat", "Nullables", "Sockets", "Unicode"]
git-tree-sha1 = "e2f6776e8bfd310b2ade13fba1faf99d8967d58f"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.17.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Measures]]
deps = ["Compat"]
git-tree-sha1 = "9cdd05418a7f2f7ce534014285edf01f465d6961"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.2.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[Nullables]]
deps = ["Compat"]
git-tree-sha1 = "23258f849603ad4fed3ce7dbcb8c0658920fa5ef"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "0.0.5"

[[OffsetArrays]]
deps = ["Compat"]
git-tree-sha1 = "36c31ad831fc3d35cd39350be56c79fa589281a8"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.5.0"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotThemes]]
deps = ["PlotUtils"]
git-tree-sha1 = "af580e3b977710c4c859a322b2d433413657121b"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "0.2.0"

[[PlotUtils]]
deps = ["Colors", "Reexport"]
git-tree-sha1 = "d42063f288d897ff5563fd694de0c389573ca9e5"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "0.4.4"

[[Plots]]
deps = ["Contour", "FixedPointNumbers", "GR", "JSON", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "RecipesBase", "Reexport", "Requires", "Showoff", "StaticArrays", "StatsBase"]
git-tree-sha1 = "9d8426356fb2800a8c76c3d3df734eae79948a41"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "0.17.2"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["Compat", "DataStructures"]
git-tree-sha1 = "50556973bf81b325584f8a92cfd57cbfa73cb303"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "0.2.1"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Ratios]]
git-tree-sha1 = "68d922178459eeb99a54fef8aad69fc76cc6682f"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.2.0"

[[RecipesBase]]
git-tree-sha1 = "fbcfab4806fbafbd2badc4cdc804c374caf01523"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.3.1"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "36e27b810e096ab501655e4b841b779cd9adaf33"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[Showoff]]
deps = ["Compat"]
git-tree-sha1 = "9cb3f3bc5819a5142706cd185d76801c7d292809"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["Compat", "DataStructures"]
git-tree-sha1 = "748c3ad6f150b685f1582906d1f9dba8834dd6db"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.2.1"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["Compat", "InteractiveUtils", "LinearAlgebra", "Random"]
git-tree-sha1 = "39adecbac9304fe6991920bd10fc67b67766275f"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.7.2"

[[StatsBase]]
deps = ["Compat", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Test"]
git-tree-sha1 = "53ae4232e9f1d7ffda8c38f80437136baed595bd"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.23.0"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "497524e8b703e67caf20cc086d20235852041fe4"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.2"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"

[[WoodburyMatrices]]
deps = ["Compat"]
git-tree-sha1 = "1ff67b5a5b5c446a71527c5ef260f046d59ca136"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.2.2"
