[[AxisAlgorithms]]
deps = ["WoodburyMatrices"]
git-tree-sha1 = "5d7f12d7f1a53ee5fd31d5b05b7f09033703fba8"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "2573aaad07cbbe21526e055bea3e995abc9e7c99"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "IterativeEigensolvers", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "SuiteSparse", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "2d63205c29efd9211fb2e10788c20587b4a5af5f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.65.1"

[[DataStructures]]
deps = ["Compat", "REPL"]
git-tree-sha1 = "abc05631fbe6e6a62c60f37bf644df87d5470fe4"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.8.3"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["Compat"]
git-tree-sha1 = "0e9a957a5c1cc5d06e54aab3b8b9c4c495253269"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.4.4"

[[Documenter]]
deps = ["Compat", "DocStringExtensions", "Logging", "REPL"]
git-tree-sha1 = "4fc4abdb5ac20ece943ff6e0a7e2a254d148f434"
uuid = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
version = "0.18.0"

[[DualNumbers]]
deps = ["Calculus", "Compat", "NaNMath"]
git-tree-sha1 = "2e0ed59cc68abac54a786b4810be0c272db90c28"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.3.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "Compat", "DualNumbers", "Ratios", "ShowItLikeYouBuildIt", "WoodburyMatrices"]
git-tree-sha1 = "430c639cdd802f625904023880ea4b2760df9e10"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.7.3"

[[IterativeEigensolvers]]
uuid = "de555fa4-b82f-55e7-8b71-53f60bbc027d"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[OffsetArrays]]
deps = ["Compat"]
git-tree-sha1 = "36c31ad831fc3d35cd39350be56c79fa589281a8"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.5.0"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["Compat", "DataStructures"]
git-tree-sha1 = "50556973bf81b325584f8a92cfd57cbfa73cb303"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "0.2.1"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Ratios]]
git-tree-sha1 = "68d922178459eeb99a54fef8aad69fc76cc6682f"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.2.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WoodburyMatrices]]
deps = ["Compat"]
git-tree-sha1 = "1ff67b5a5b5c446a71527c5ef260f046d59ca136"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.2.2"
