[[AxisAlgorithms]]
deps = ["WoodburyMatrices"]
git-tree-sha1 = "5d7f12d7f1a53ee5fd31d5b05b7f09033703fba8"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "2573aaad07cbbe21526e055bea3e995abc9e7c99"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.0"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "903ab7490d404e313fc9bf53942e28b1ba9307e8"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.11"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "456524c5dc9af774533e4133f9989296053c5bdd"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.2"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "cec56a50029f40f4c13e4f25bf84964fde31905a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "c478aec93ea90bb99c307a92df17a76131bf275f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.0"

[[Contour]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "4e244ce551b993b721a6dbbd040b5f3d7cba0f48"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.0"

[[CustomUnitRanges]]
git-tree-sha1 = "745a202720c1e848936c7808177841c36446948c"
uuid = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
version = "0.1.0"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Missings", "Reexport", "SortingAlgorithms", "StatsBase", "TranscodingStreams", "WeakRefStrings"]
git-tree-sha1 = "a79e5f3756177f9135f6c2318f4d90bc40da8feb"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.11.7"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["Compat"]
git-tree-sha1 = "0d767d338c201b1b2064e2186a0b63ac1e55dbb1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.4.5"

[[Documenter]]
deps = ["Compat", "DocStringExtensions", "Logging", "REPL"]
git-tree-sha1 = "db9efaced47fd05e8fa5f6ec3f6925dc2f1425aa"
uuid = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
version = "0.19.1"

[[DualNumbers]]
deps = ["Calculus", "Compat", "NaNMath"]
git-tree-sha1 = "fc9c09319884bdc80f66993197dfc300051781b9"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.4.0"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "53fae3f45b6782dad91e932d941b0bf862110641"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.1"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[GR]]
deps = ["DelimitedFiles", "Random", "Serialization", "Sockets", "Test"]
git-tree-sha1 = "b0a1d37d216fe143020b5d7d49c4fdc18642f150"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.31.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "Compat", "DualNumbers", "Ratios", "ShowItLikeYouBuildIt", "WoodburyMatrices"]
git-tree-sha1 = "430c639cdd802f625904023880ea4b2760df9e10"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.7.3"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Measures]]
deps = ["Compat"]
git-tree-sha1 = "9cdd05418a7f2f7ce534014285edf01f465d6961"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.2.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "7c4ca0f266081385e2ecf57fb210034f970cce5d"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotThemes]]
deps = ["PlotUtils", "Requires", "Test"]
git-tree-sha1 = "f3afd2d58e1f6ac9be2cea46e4a9083ccc1d990b"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "0.3.0"

[[PlotUtils]]
deps = ["Colors", "Dates", "Printf", "Reexport", "Test"]
git-tree-sha1 = "99c6f7f9111d49209cd5859f8fc407bc030defad"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "0.5.0"

[[Plots]]
deps = ["Contour", "FixedPointNumbers", "GR", "JSON", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "RecipesBase", "Reexport", "Requires", "Showoff", "StaticArrays", "StatsBase"]
git-tree-sha1 = "950065e8f296f65ea5f5876a0d0a768267198512"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "0.17.4"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "d136ea5b320aad2b1a8c3196e642c2282e601660"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.0"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Ratios]]
git-tree-sha1 = "68d922178459eeb99a54fef8aad69fc76cc6682f"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.2.0"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "298e774bc0fd26b7011358fc9ff0223b4e81aaa6"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.4.0"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[Showoff]]
deps = ["Compat"]
git-tree-sha1 = "9cb3f3bc5819a5142706cd185d76801c7d292809"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d998a83bc2cd507e12b08203e7523f2e60ac9ee6"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.2"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "d10e1e4b8fb8c6c50a1458c8e0de8f7abd0fc144"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.3"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "742748a6eec707d55c818747a37ed528688b3ad3"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.4.0"
